version: '3.8'

services:
  otel-wrapper:
    image: otel-wrapper:latest
    build:
      context: ../src
      dockerfile: ../deploy/Dockerfile
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - otel-net
    configs:
      - source: automation_script
        target: /config/automation_script.py
        mode: 444
    entrypoint: [ "python", "/config/automation_script.py" ]

configs:
  automation_script:
    file: ../scripts/automation_script.py

networks:
  otel-net:
    external: true
